# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import drone_pb2 as drone__pb2


class ClientConnectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.connect = channel.unary_unary(
        '/ClientConnection/connect',
        request_serializer=drone__pb2.ConnectionRequest.SerializeToString,
        response_deserializer=drone__pb2.ConnectionResponse.FromString,
        )


class ClientConnectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def connect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClientConnectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'connect': grpc.unary_unary_rpc_method_handler(
          servicer.connect,
          request_deserializer=drone__pb2.ConnectionRequest.FromString,
          response_serializer=drone__pb2.ConnectionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ClientConnection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
